### ISSUE TITLE
Поддержку Linux в студию!

### ISSUE THREAD

**Issue by sleirsgoevy** [MikailBag/opl#2]
Команда для прогона препроцессора: g++ -E src.cpp -o dst.cpp

**Comment by MikailBag** [comment]
Как препроцесснуть в stdout?

**Comment by sleirsgoevy** [comment]
g++ -E src.cpp -o /dev/stdout

**Comment by MikailBag** [comment]
А более кроссплатфоремнно?

**Comment by sleirsgoevy** [comment]
а для венды код уже есть

**Comment by MikailBag** [comment]
Для винды + gcc еще нет

**Comment by MikailBag** [comment]
сейчас запушу

**Comment by MikailBag** [comment]
можешь тестить

**Comment by MikailBag** [comment]
Кстати если покроешь чем-нибудь будет вообще отлично (хотя бы для g++)
